project:
  type: website
  output-dir: docs

website:
  title: "Duc Thai Tran"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: posts.qmd
        text: Writing
      - href: photos.qmd
        text: Photos
      - href: videos.qmd
        text: Videos
    right:
      - icon: envelope
        href: mailto:your.email@students.mq.edu.au

format:
  html:
    theme: cosmo
    css: styles.css
    mainfont: Georgia
    backgroundcolor: "#E8DCB9"
    linkcolor: "#EE7674"
