project:
  type: website
  output-dir: _site

website:
  title: "Duc Thai Tran"
  navbar:
    background: light
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Personal works"
        href: personal.qmd
    right:
      - icon: envelope
        href: "mailto:ducthai.tran@outlook.com"
        aria-label: Email
      - icon: github
        href: "https://github.com/dr-thaitran"
        aria-label: GitHub

format:
  html:
    theme: theme.scss
    include-in-header: head.html
    toc: false
    page-layout: full
    title-block-banner: false
    grid:
      body-width: 1180px
